version: "3.2"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=8080
      - DB_URL=mongodb://root:mongo@db
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
